# NOTE: Generated By InterfaceTester 5.0.1
# FROM: chain.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseChain(InterfaceTester):

    config = (
        Config("SOAP：XML 取值与多步链路")
        .variables(
            **{
                "soap_action": "urn:demo#Query",
                "code_path": "code",
                "soap_capture": {
                    "SOAP_CAPTURED_CODE": "code",
                    "SOAP_CAPTURED_MESSAGE": "message",
                },
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId>U1001</ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n',
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("步骤1：查询，并把 code / message 抓到环境变量")
            .post("/svc/query")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .teardown_hook("${xml_field($response, code)}", "code")
            .teardown_hook("${capture_xml($response, $soap_capture)}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", ["code", "0000"])
            .assert_contains("text", "<ns1:code>$code</ns1:code>")
        ),
        Step(
            RunRequest("步骤2：把上一步抓到的值带到下一个请求（跨步骤只能走 ${ENV()}）")
            .post("/svc/query?code=${ENV(SOAP_CAPTURED_CODE)}")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "X-From-Env": "${ENV(SOAP_CAPTURED_CODE)}",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", ["code", "${ENV(SOAP_CAPTURED_CODE)}"])
            .assert_contains("text", "<ns1:code>${ENV(SOAP_CAPTURED_CODE)}</ns1:code>")
            .assert_contains(
                "text", "<ns1:message>${ENV(SOAP_CAPTURED_MESSAGE)}</ns1:message>"
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseChain().test_start()
