# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_string_assert.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastStringAssert(InterfaceTester):

    config = (
        Config("对照：A0 字符串断言在 XML 上的真实行为")
        .variables(
            **{
                "entity": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body><ns1:Ping xmlns:ns1="http://demo.example.com/svc"/></soap:Body>\n</soap:Envelope>\n'
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest(
                '断「报文以 < 开头」通过——但它比的是 str(bytes)，即 "b\'<?xml…"，语义完全错位'
            )
            .post("/svc/query-broken")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "urn:demo#Query",
                }
            )
            .with_data("$entity")
            .validate()
            .assert_equal("status_code", 200)
            .assert_startswith("body", "b'")
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastStringAssert().test_start()
