# NOTE: Generated By InterfaceTester 5.0.1
# FROM: fault.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseFault(InterfaceTester):

    config = (
        Config("SOAP：Fault 断言模板")
        .variables(
            **{
                "soap_action": "urn:demo#Query",
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId></ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n',
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("参数校验失败（soap:Fault / HTTP 500）")
            .post("/svc/fault")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 500)
            .assert_soap_fault("body", "Invalid parameter")
            .assert_xpath_match("body", "Fault")
            .assert_xpath_match("body", ["faultcode", "soap:Client"])
            .assert_xpath_match("body", ["faultstring", "Invalid parameter: userId"])
            .assert_xpath_match(
                "body", ["{http://demo.example.com/svc}code", "SVC-1002"]
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseFault().test_start()
