# NOTE: Generated By InterfaceTester 5.0.1
# FROM: query.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseQuery(InterfaceTester):

    config = (
        Config("SOAP：XML 结构化断言")
        .variables(
            **{
                "soap_action": "urn:demo#Query",
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId>U1001</ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n',
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("正常响应：先断 HTTP，再断业务码与金额")
            .post("/svc/query")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", ["code", "0000"])
            .assert_xpath_match("body", ["amount", "1234.50"])
            .assert_xpath_match("body", ["{http://demo.example.com/svc}code", "0000"])
        ),
        Step(
            RunRequest("前缀从 ns1 漂移成 abc：同一份契约，断言照过")
            .post("/svc/query-drift")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", ["code", "0000"])
            .assert_xpath_match("body", ["message", "成功"])
        ),
        Step(
            RunRequest("明细条数与属性选择（列表类报文的常见断言）")
            .post("/svc/items")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "urn:demo#Items",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_count("body", ["item", 3])
            .assert_xpath_match("body", "item[@id='2']")
            .assert_xpath_match("body", ["name", "丙"])
        ),
    ]


if __name__ == "__main__":
    TestCaseQuery().test_start()
