# NOTICE: Generated By InterfaceTester.
import json
import os
import time

import pytest
from loguru import logger

from interfacetester.utils import get_platform, ExtendJSONEncoder


@pytest.fixture(scope="session", autouse=True)
def session_fixture(request):
    """setup and teardown each task"""
    logger.info("start running testcases ...")

    start_at = time.time()

    yield

    logger.info("task finished, generate task summary for --save-tests")

    summary = {
        "success": True,
        "stat": {
            "testcases": {"total": 0, "success": 0, "fail": 0},
            "teststeps": {"total": 0, "failures": 0, "successes": 0},
        },
        "time": {"start_at": start_at, "duration": time.time() - start_at},
        "platform": get_platform(),
        "details": [],
    }

    for item in request.node.items:
        # 0918-3（H4 家族）：不能因为**一个** item 取不到汇总就丢掉整份 summary。
        # 两个真实场景：
        #   ① 项目根同时存在「非本框架」的 pytest/unittest 用例（很常见：框架用例 + 工具脚本
        #      放同一个仓库）——它们的 `item.instance` 没有 `get_summary`，
        #      修复前会直接 AttributeError，让 session fixture 报错、summary 全丢；
        #   ② 某个用例的汇总本身出问题（历史上有 H4 的 ParamsError）。
        # 现在的口径：非框架用例跳过（debug），取汇总失败记 error 后跳过，其余继续。
        get_summary = getattr(getattr(item, "instance", None), "get_summary", None)
        if not callable(get_summary):
            logger.debug(f"--save-tests: 跳过非 InterfaceTester 用例 {item.nodeid}")
            continue

        try:
            testcase_summary = get_summary()
        except Exception as ex:
            # NOTICE（两层转义，实测踩过两次）：
            # 1) 换行必须写成**双反斜杠 + n**：本模板是 compat.py 里的普通三引号字符串，
            #    写单个反斜杠 n 会在 compat.py 被解析时变成**真实换行**；
            #    若它出现在 f-string 里 → 跨行 → SyntaxError: unterminated f-string literal；
            #    若它出现在**注释**里 → 注释被从中间截断，后半段变成裸代码 → 同样 SyntaxError。
            # 2) 花括号必须写**单层**：本模板只用 `.replace()` 做占位符替换（没走 format），
            #    写成双层会原样留在生成文件里、不被插值。
            logger.error(
                f"--save-tests: 收集用例汇总失败，已跳过该用例（其余用例与汇总文件不受影响）\n"
                f"  nodeid: {item.nodeid}\n"
                f"  {type(ex).__name__}: {ex}"
            )
            continue

        summary["success"] &= testcase_summary.success

        # NOTICE（批次 A / M8）：统计必须按**记录里实际的成功/失败条数**算，
        # 不能再用 `len(step_results) - 1` 去猜。
        #
        # 修复前失败分支写的是「成功数 += 条数 - 1、失败数 += 1」，即**硬编码了**
        # 「一个失败用例 = 恰好一条失败 step，其余全成功」这个假设。而 H1 的修复
        # 刚刚引入了「`success == False` 且 `step_results == []`」这种**合法**组合
        # （用例在 step 之外失败：配置解析失败、`teststeps` 装配抛异常…），
        # 于是算出 `successes = 0 - 1 = -1`（实测 summary.json 里真的出现负数），
        # 同时 `failures: 1` 与 `records: []` 也自相矛盾。
        #
        # 现在逐条数：`total` = 记录的条数，`successes`/`failures` = 其中两者的条数。
        # 用例级失败但一条 step 都没跑时，`testcases.fail` 增 1、`teststeps` 三项都不动——
        # 这是**如实**的（确实没有任何 step 被执行过），比编一个失败数更可信。
        #
        # NOTICE: 本模板是 compat.py 里的普通三引号字符串，只用 `.replace()` 做占位符替换
        # （没走 format/f-string）——**不要**在这里写 f-string 或双层花括号，
        # 换行也要写成双反斜杠 + n，理由见上面「两层转义」那条 NOTICE。
        step_total = len(testcase_summary.step_results)
        step_successes = 0
        for step_result in testcase_summary.step_results:
            if step_result.success:
                step_successes += 1
        step_failures = step_total - step_successes

        summary["stat"]["testcases"]["total"] += 1
        summary["stat"]["teststeps"]["total"] += step_total
        summary["stat"]["teststeps"]["successes"] += step_successes
        summary["stat"]["teststeps"]["failures"] += step_failures
        if testcase_summary.success:
            summary["stat"]["testcases"]["success"] += 1
        else:
            summary["stat"]["testcases"]["fail"] += 1

        testcase_summary_json = testcase_summary.model_dump()
        testcase_summary_json["records"] = testcase_summary_json.pop("step_results")
        summary["details"].append(testcase_summary_json)

    summary_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "logs",
        "probe_silent.summary.json",
    )
    summary_dir = os.path.dirname(summary_path)
    os.makedirs(summary_dir, exist_ok=True)

    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, cls=ExtendJSONEncoder)

    logger.info(f"generated task summary: {summary_path}")

