# NOTE: Generated By InterfaceTester 5.0.1
# FROM: login_flow.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseLoginFlow(InterfaceTester):

    config = (
        Config("登录拿 token 再带 token 调接口")
        .base_url("${ENV(BASE_URL)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("登录获取 token")
            .post("/api/login")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "admin", "password": "123456"})
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("用 token 查询用户信息")
            .get("/api/user/info")
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.data.username", "admin")
            .assert_equal("body.data.role", "admin")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginFlow().test_start()
