# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_prefix_literal.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastPrefixLiteral(InterfaceTester):

    config = (
        Config("对照：原始 XPath 的前缀是字面量（第 2 步会报错）")
        .variables(
            **{
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId>U1001</ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n'
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("前缀写对：abc: 与报文声明一致 → 通过")
            .post("/svc/query-drift")
            .with_headers(**{"Content-Type": "text/xml; charset=utf-8"})
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", "//abc:code/text()")
        ),
        Step(
            RunRequest("前缀写错：报文声明是 abc:，断言写 ns1: → 报错（未声明前缀）")
            .post("/svc/query-drift")
            .with_headers(**{"Content-Type": "text/xml; charset=utf-8"})
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", "//ns1:code/text()")
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastPrefixLiteral().test_start()
