# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_xsd_violation.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastXsdViolation(InterfaceTester):

    config = (
        Config("对照：业务码违反 XSD 约束（本例会失败）")
        .variables(
            **{
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId>U1001</ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n'
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("业务码 1002 违反 pattern 0[0-9]{3} → 失败，并指到具体节点")
            .post("/svc/query-badcode")
            .with_headers(**{"Content-Type": "text/xml; charset=utf-8"})
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xml_schema_match(
                "body",
                {"xpath": "QueryResponse", "xsd": "schemas/query.xsd"},
                "业务码不符合契约",
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastXsdViolation().test_start()
