# NOTE: Generated By InterfaceTester 5.0.1
# FROM: xpath.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseXpath(InterfaceTester):

    config = (
        Config("内核 XML/XPath 断言（lxml extra）")
        .variables(
            **{
                "soap_action": "urn:demo#Query",
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId>U1001</ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n',
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("两种写法混用：简化写法（前缀无关）+ 原始 XPath")
            .post("/svc/query")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", ["code", "0000"])
            .assert_xpath_match("body", "//ns1:code/text()")
            .assert_xpath_match("body", ["string(//ns1:amount)", "1234.50"])
        ),
        Step(
            RunRequest("前缀从 ns1 漂移成 abc：简化写法与 local-name() 都照过")
            .post("/svc/query-drift")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_match("body", ["code", "0000"])
            .assert_xpath_match("body", "//*[local-name()='message']")
        ),
        Step(
            RunRequest("明细类报文：count()、位置谓词、多级路径、属性取值、轴")
            .post("/svc/items")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "urn:demo#Items",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xpath_count("body", ["item", 3])
            .assert_xpath_count("body", ["//ns1:item", 3])
            .assert_xpath_count("body", ["count(//ns1:item)", 3])
            .assert_xpath_match("body", ["(//ns1:item)[2]/ns1:name", "乙"])
            .assert_xpath_match("body", ["//ns1:item[@id='3']/@id", "3"])
            .assert_xpath_match(
                "body", "//ns1:item[@id='1']/ancestor::ns1:ItemsResponse"
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseXpath().test_start()
