# NOTE: Generated By InterfaceTester 5.0.1
# FROM: xsd.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseXsd(InterfaceTester):

    config = (
        Config("XSD 契约校验（xml_schema_match）")
        .variables(
            **{
                "soap_action": "urn:demo#Query",
                "envelope": '<?xml version="1.0" encoding="utf-8"?>\n<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\n  <soap:Body>\n    <ns1:QueryRequest xmlns:ns1="http://demo.example.com/svc">\n      <ns1:userId>U1001</ns1:userId>\n    </ns1:QueryRequest>\n  </soap:Body>\n</soap:Envelope>\n',
            }
        )
        .base_url("${soap_base_url()}")
    )

    teststeps = [
        Step(
            RunRequest("先定位业务元素，再按 XSD 校验（推荐写法）")
            .post("/svc/query")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xml_schema_match(
                "body", {"xpath": "QueryResponse", "xsd": "schemas/query.xsd"}
            )
        ),
        Step(
            RunRequest("前缀漂移：XSD 按命名空间 URI 匹配，换前缀照样通过")
            .post("/svc/query-drift")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "$soap_action",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xml_schema_match(
                "body", {"xpath": "QueryResponse", "xsd": "schemas/query.xsd"}
            )
        ),
        Step(
            RunRequest("明细列表：1~3 条 + 必填属性（xs:include 的多文件 XSD）")
            .post("/svc/items")
            .with_headers(
                **{
                    "Content-Type": "text/xml; charset=utf-8",
                    "SOAPAction": "urn:demo#Items",
                }
            )
            .with_data("$envelope")
            .validate()
            .assert_equal("status_code", 200)
            .assert_xml_schema_match(
                "body", {"xpath": "ItemsResponse", "xsd": "schemas/items.xsd"}
            )
            .assert_xml_schema_match(
                "body", {"xpath": "(//ns1:item)[2]", "xsd": "schemas/items.xsd"}
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseXsd().test_start()
