# NOTE: Generated By InterfaceTester 5.0.1
# FROM: validate.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseValidate(InterfaceTester):

    config = Config("basic test with httpbin").base_url("${get_httpbin_server()}")

    teststeps = [
        Step(
            RunRequest("validate response with json path")
            .get("/get")
            .with_params(**{"a": 1, "b": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.a", "1")
            .assert_equal("body.args.b", "2")
        ),
        Step(
            RunRequest("validate response with custom comparator in debugtalk.py")
            .get("/get")
            .with_params(**{"a": 1, "b": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_sum_status_code("status_code", 2)
            .assert_equal("body.args.a", "1")
        ),
    ]


if __name__ == "__main__":
    TestCaseValidate().test_start()
