"""0918-3（批次 3）：`--save-tests` 可观测性 —— H4（丢证据）+ M6（覆盖用户文件）。

两个缺陷在同一条链路上，所以放一个文件里：

    hrun ... --save-tests
      └─ compat.ensure_cli_args
           └─ compat._generate_conftest_for_summary   ← M6：无条件覆写项目根的 conftest.py
                └─ 生成物里的 session_fixture
                     └─ item.instance.get_summary()   ← H4：导出变量缺失时抛异常
                          └─ runner.get_export_variables()

**H4 的实际后果**（修复前实测）::

    $ hrun case.yml --save-tests
    1 passed ... 1 error   (exit code 1)
    E  ParamsError: failed to export variable never_set_var from session variables {}
    logs/tmp/case.summary.json   ← 没有生成

即：用例本身**通过**，却多一个 ERROR + 非零退出码，且**汇总文件根本没写出来**。
真实场景（step 失败 → export 的变量没提取到）更糟：**真失败时汇总生成反而崩掉、证据丢失**。

**M6 的实际后果**：项目根已有的 `conftest.py`（用户自己的 fixture）被整体覆盖、无备份。
仓库里 `examples/postman_echo/request_methods/conftest.py` 就是一个手写 conftest
（含 `testcase_fixture` 自定义逻辑），第 58 行正是 `request.instance.get_summary()` ——
**说明 H4 那条路径在真实项目里就是这么被调用的**。
"""
import json
import os
import shutil
import subprocess
import sys
import unittest
import uuid

from loguru import logger

from interfacetester import (
    Config,
    InterfaceTester,
    RunRequest,
    RunTestCase,
    Step,
    compat,
    exceptions,
    loader,
)
from interfacetester.utils import HTTP_BIN_URL

CONFTEST_MARKER = "# NOTICE: Generated By InterfaceTester."

FOREIGN_CONFTEST = '''"""用户自己的 conftest.py（不是生成的）。"""
import pytest


@pytest.fixture(scope="session", autouse=True)
def my_own_fixture():
    """这个 fixture 一旦被覆盖，用户的自定义逻辑就永久丢失了。"""
    yield


@pytest.fixture(scope="function", autouse=True)
def my_function_fixture():
    yield
'''


def _make_tmp_project(with_conftest: str = None, conftest_name: str = "conftest.py"):
    """建一个临时项目（放在 logs/ 下：已被 .gitignore 覆盖，也不会被 pytest 收集）。

    必须带 `debugtalk.py`：这样 `load_project_meta` 才能确定地把 RootDir 定位到这个目录，
    生成的 conftest.py 才会落在这里（否则会落到 cwd，也就是仓库根 —— 这正是
    缺陷汇总里 M6 的现场）。
    """
    tmp_dir = os.path.join(os.getcwd(), "logs", f"tmp_save_{uuid.uuid4().hex[:8]}")
    os.makedirs(tmp_dir)

    with open(os.path.join(tmp_dir, "debugtalk.py"), "w", encoding="utf-8") as f:
        f.write("# 项目标记：让 RootDir 稳定落在这个目录\n")
    yml_path = os.path.join(tmp_dir, "case.yml")
    with open(yml_path, "w", encoding="utf-8") as f:
        f.write(
            f"config:\n"
            f"    name: save-tests probe\n"
            f"    base_url: {HTTP_BIN_URL}\n"
            f"teststeps:\n"
            f"    -\n"
            f"        name: simple get\n"
            f"        request:\n"
            f"            method: GET\n"
            f"            url: /status/200\n"
            f"        validate:\n"
            f'            - eq: ["status_code", 200]\n'
        )

    if with_conftest is not None:
        with open(
            os.path.join(tmp_dir, conftest_name), "w", encoding="utf-8"
        ) as f:
            f.write(with_conftest)

    return tmp_dir, yml_path


def _capture_warnings(action):
    """执行 action 并返回 loguru 捕获到的 WARNING 文本列表。"""
    messages = []
    sink_id = logger.add(messages.append, level="WARNING", format="{message}")
    try:
        action()
    finally:
        logger.remove(sink_id)
    return messages


# ===========================================================================
# H4：导出变量缺失不能把"通过"变成"error"，也不能丢掉汇总
# ===========================================================================
class TestMissingExportVariableDoesNotBreakSummary(unittest.TestCase):
    """H4：`get_summary()`（**报告路径**）不得因为导出变量缺失而抛异常。

    严格检查本身是对的，但它属于**运行时变量传递**那条路径
    （`step_testcase.run_step_testcase` 要把被引用用例的变量带给外层 step）；
    报告路径不该因为一个变量没导出就整个崩掉——那会连带丢掉整份 summary。
    """

    def setUp(self):
        loader.reset_project_meta()

    def tearDown(self):
        loader.reset_project_meta()

    def _run_case_with_declared_export(self, export_names):
        """跑一个**会通过**的用例，但 `config.export` 声明了从未被 extract 的变量。"""

        class _ExportProbeCase(InterfaceTester):
            config = Config("export probe").base_url(HTTP_BIN_URL).export(*export_names)
            teststeps = [
                Step(
                    RunRequest("ok step")
                    .get("/status/200")
                    .validate()
                    .assert_equal("status_code", 200)
                )
            ]

        return _ExportProbeCase().test_start()

    def test_get_summary_does_not_raise(self):
        """核心回归：`get_summary()` 不能抛 `ParamsError`。

        修复前它抛 `ParamsError: failed to export variable ...`，而这个异常发生在
        `session_fixture` 的 **teardown** 里 —— 于是每个用例都被记一个 ERROR，
        退出码变 1，`summary.json` 也不会被写出来。
        """
        runner = self._run_case_with_declared_export(["never_set_var"])

        summary = runner.get_summary()  # 修复前：这里抛 ParamsError

        self.assertTrue(summary.success, "用例本身是通过的，汇总也应当记为成功")
        self.assertEqual(summary.in_out.export_vars, {})
        self.assertEqual(len(summary.step_results), 1)

    def test_missing_export_is_reported_as_warning(self):
        """不能静默吞掉——缺失的导出变量必须留下告警（否则是另一种"丢证据"）。"""
        runner = self._run_case_with_declared_export(["never_set_var"])

        messages = _capture_warnings(runner.get_summary)

        self.assertTrue(
            any("never_set_var" in message for message in messages),
            f"缺失的导出变量没有被报告出来：{messages}",
        )

    def test_present_export_variable_is_still_exported(self):
        """反向断言：能导出的变量照旧导出（不能因为"宽松"就把功能改没了）。

        NOTICE（0919-13 / 批次 E）：这里断言的是**运行期取值**（`get_export_variables`）。
        修复前 `summary.in_out.export_vars` **就是**运行期取值源，所以当时直接断言 summary；
        现在 summary 里的是**脱敏后的展示副本**（`token` 命中 `SENSITIVE_KEYWORDS`，
        显示为 `******`）——两者必须分开断言，混在一起就会把
        「运行期取到了真值」和「报告里没有明文」两件事都测不出来。
        """

        class _GoodExportCase(InterfaceTester):
            config = Config("good export").base_url(HTTP_BIN_URL).export("token")
            teststeps = [
                Step(
                    RunRequest("extract then export")
                    .get("/status/200")
                    .extract()
                    .with_jmespath("status_code", "token")
                    .validate()
                    .assert_equal("status_code", 200)
                )
            ]

        runner = _GoodExportCase().test_start()

        # 运行期：真值（变量传递要靠它）
        self.assertEqual(runner.get_export_variables(strict=True), {"token": 200})
        # 展示副本：敏感键名脱敏（summary.json / HTML 报告里不该有明文）
        self.assertEqual(runner.get_summary().in_out.export_vars, {"token": "******"})

    def test_referenced_testcase_export_is_still_strict(self):
        """**反向断言（最重要的一条）**：变量传递路径必须保持严格。

        被引用用例声明了 `export` 却没真的导出 → 外层 step 的契约没被满足，
        必须**响亮地失败**，不能因为报告路径放宽了就把这条也一起放过去。
        """

        class _RefCase(InterfaceTester):
            config = Config("referenced case").base_url(HTTP_BIN_URL).export(
                "never_set_var"
            )
            teststeps = [
                Step(
                    RunRequest("ref step")
                    .get("/status/200")
                    .validate()
                    .assert_equal("status_code", 200)
                )
            ]

        class _ReferringCase(InterfaceTester):
            config = Config("referring case").base_url(HTTP_BIN_URL)
            teststeps = [Step(RunTestCase("call ref").call(_RefCase))]

        with self.assertRaises(Exception) as ctx:
            _ReferringCase().test_start()

        self.assertIn("never_set_var", str(ctx.exception))


class TestSaveTestsSummaryJsonIsWritten(unittest.TestCase):
    """H4 端到端：`hrun --save-tests` 必须**真的产出** summary.json。

    用子进程跑，因为它才是用户的真实路径（`main_run` → `ensure_cli_args` →
    `pytest.main`），也避免同进程嵌套 pytest 会话的不稳定（见 tests/cli_test.py 的 NOTES）。
    """

    def setUp(self):
        self.tmp_dir, self.yml_path = _make_tmp_project()

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def _write_case_with_declared_export(self):
        with open(self.yml_path, "w", encoding="utf-8") as f:
            f.write(
                f"config:\n"
                f"    name: summary probe\n"
                f"    base_url: {HTTP_BIN_URL}\n"
                f"    export:\n"
                f"        - never_set_var\n"
                f"teststeps:\n"
                f"    -\n"
                f"        name: simple get\n"
                f"        request:\n"
                f"            method: GET\n"
                f"            url: /status/200\n"
                f"        validate:\n"
                f'            - eq: ["status_code", 200]\n'
            )

    def test_summary_json_is_written_and_exit_code_is_zero(self):
        self._write_case_with_declared_export()

        # NOTICE（0918-8 / L28）：子进程是**框架自己的 CLI**，它会把自己 stdout/stderr
        # 强制成 UTF-8（M10/L27）→ 父进程必须显式按 UTF-8 解码。
        # 修复前这里用 `text=True`（按 locale 解码，本机 cp936）：CJK locale 下
        # 读取线程会抛 UnicodeDecodeError、`proc.stdout` 变成 **None**，
        # 而 `f"{proc.stdout}"` 打印出来是 "None"——排查时看不到任何真实输出。
        env = dict(os.environ)
        env["PYTHONIOENCODING"] = "utf-8"
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "interfacetester",
                "run",
                "case.yml",
                "--save-tests",
            ],
            cwd=self.tmp_dir,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env,
            timeout=180,
        )

        summary_path = os.path.join(self.tmp_dir, "logs", "case.summary.json")

        self.assertTrue(
            os.path.isfile(summary_path),
            f"summary.json 没有被生成（H4）\n"
            f"returncode={proc.returncode}\nstdout=\n{proc.stdout}\nstderr=\n{proc.stderr}",
        )
        self.assertEqual(
            proc.returncode, 0, f"用例通过却返回非 0：\n{proc.stdout}\n{proc.stderr}"
        )

        with open(summary_path, encoding="utf-8") as f:
            summary = json.load(f)

        self.assertTrue(summary["success"])
        self.assertEqual(summary["stat"]["testcases"]["total"], 1)
        self.assertEqual(summary["stat"]["testcases"]["fail"], 0)


# ===========================================================================
# H1（0919-18）：失败用例不得被报成 success，失败那一步必须留在报告里
# ===========================================================================
def _step_block(name: str, expect_status: int) -> str:
    """生一个「GET /status/200 + eq status_code」的 teststep YAML 块。"""
    return (
        f"    -\n"
        f"        name: {name}\n"
        f"        request:\n"
        f"            method: GET\n"
        f"            url: /status/200\n"
        f"        validate:\n"
        f'            - eq: ["status_code", {expect_status}]\n'
    )


class TestFailedCaseIsNotReportedAsSuccess(unittest.TestCase):
    """H1 端到端：走真 CLI（`hrun run case.yml --save-tests`）核对 summary.json。

    ## 修复前的现场（实测，2 步用例、第 2 步断言 `status_code == 999`）

    ```text
    内层 pytest：1 failed、子进程退出码 1        ← 唯一没说谎的地方
    logs/case.summary.json：
      success = True
      stat    = {'testcases': {'total': 1, 'success': 1, 'fail': 0},
                 'teststeps': {'total': 1, 'failures': 0, 'successes': 1}}
      details[0].success = True
      details[0].records = [只有 step1]          ← 失败那一步整体消失
    ```

    两处根因（都在 `runner.py`，见 `__failed` / `__record_failed_step` 的 NOTICE）：

    1. `__run_step` 在重试耗尽时直接 `raise`，**跳过** `__step_results.append(step_result)`
       ——失败那一步的 `data`（`validators` + 请求响应记录）随异常一起被丢掉；
    2. `get_summary()` 的 `summary_success` **只**由 `__step_results` 推导，
       「本用例抛过异常」这个事实完全不参与。

    现在：三个 step 模块把已建好的 `StepResult` 挂在异常上交给 runner，runner 记录它；
    另外 `__failed` 作为用例级事实来源参与 `summary_success`。
    """

    def setUp(self):
        self.tmp_dir, self.yml_path = _make_tmp_project()

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def _run_save_tests(self, steps_yaml: str):
        """写用例 → 真 CLI 跑 → 返回 (proc, summary.json 内容)。"""
        with open(self.yml_path, "w", encoding="utf-8") as f:
            f.write(
                f"config:\n"
                f"    name: h1 probe\n"
                f"    base_url: {HTTP_BIN_URL}\n"
                f"teststeps:\n"
                f"{steps_yaml}"
            )

        env = dict(os.environ)
        env["PYTHONIOENCODING"] = "utf-8"
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "interfacetester",
                "run",
                "case.yml",
                "--save-tests",
            ],
            cwd=self.tmp_dir,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env,
            timeout=180,
        )

        summary_path = os.path.join(self.tmp_dir, "logs", "case.summary.json")
        self.assertTrue(
            os.path.isfile(summary_path),
            f"summary.json 没有被生成\nreturncode={proc.returncode}\n"
            f"stdout=\n{proc.stdout}\nstderr=\n{proc.stderr}",
        )
        with open(summary_path, encoding="utf-8") as f:
            return proc, json.load(f)

    def test_failed_case_is_not_reported_as_success(self):
        """三处（`success` / `stat.testcases` / `details[].success`）都不能说谎。"""
        proc, summary = self._run_save_tests(
            _step_block("step1 ok", 200) + _step_block("step2 WILL FAIL", 999)
        )

        self.assertNotEqual(proc.returncode, 0, "失败用例不该返回 0")
        self.assertFalse(
            summary["success"], f"失败用例被报成通过（H1）：{json.dumps(summary, ensure_ascii=False)[:400]}"
        )
        self.assertEqual(
            summary["stat"]["testcases"], {"total": 1, "success": 0, "fail": 1}
        )
        self.assertFalse(summary["details"][0]["success"])

    def test_step_counts_include_the_failed_step(self):
        """`stat.teststeps` 必须把失败那一步算进去（修复前 total 少算一步）。"""
        _proc, summary = self._run_save_tests(
            _step_block("step1 ok", 200) + _step_block("step2 WILL FAIL", 999)
        )

        self.assertEqual(
            summary["stat"]["teststeps"],
            {"total": 2, "failures": 1, "successes": 1},
            "失败步骤没有进统计（消费方 compat.py 的 `len(step_results) - 1` 算法会因此错位）",
        )

    def test_failing_step_stays_in_records_with_its_evidence(self):
        """失败那一步必须在 `records` 里，且带着「哪条断言挂了」的证据。"""
        _proc, summary = self._run_save_tests(
            _step_block("step1 ok", 200) + _step_block("step2 WILL FAIL", 999)
        )

        records = summary["details"][0]["records"]
        self.assertEqual(
            [record["name"] for record in records],
            ["step1 ok", "step2 WILL FAIL"],
            f"失败那一步没进报告：{records}",
        )

        failing = records[-1]
        self.assertFalse(failing["success"])
        # 证据一：断言结果（修复前它与 StepResult 一起被丢掉）
        validators = failing["data"]["validators"]["validate_extractor"]
        self.assertEqual(validators[0]["check_result"], "fail")
        self.assertEqual(validators[0]["expect_value"], 999)
        self.assertEqual(validators[0]["check_value"], 200)
        # 证据二：这一次的请求/响应记录
        self.assertEqual(failing["data"]["success"], False)
        self.assertEqual(len(failing["data"]["req_resps"]), 1)
        self.assertEqual(
            failing["data"]["req_resps"][0]["response"]["status_code"], 200
        )

    def test_single_step_failure_still_counts_one_step(self):
        """单步用例失败：修复前 `teststeps.total` 是 **0**（列表为空）。"""
        proc, summary = self._run_save_tests(_step_block("only step fails", 999))

        self.assertNotEqual(proc.returncode, 0)
        self.assertFalse(summary["success"])
        self.assertEqual(
            summary["stat"]["teststeps"],
            {"total": 1, "failures": 1, "successes": 0},
        )
        self.assertEqual(
            [record["name"] for record in summary["details"][0]["records"]],
            ["only step fails"],
        )


class TestFailedCaseSummaryObject(unittest.TestCase):
    """单元级（不落盘）：失败之后 `get_summary()` 本身也不能说「通过」。

    `compat.py` 的 `--save-tests` 装置就是在用例失败之后调用 `get_summary()` 的，
    所以这一层必须自己站得住，不能只依赖 summary.json 的端到端用例。
    """

    def test_get_summary_is_not_successful_after_a_step_fails(self):
        class _FailOnSecond(InterfaceTester):
            config = Config("h1 unit probe").base_url(HTTP_BIN_URL)
            teststeps = [
                Step(
                    RunRequest("first ok")
                    .get("/status/200")
                    .validate()
                    .assert_equal("status_code", 200)
                ),
                Step(
                    RunRequest("second fails")
                    .get("/status/200")
                    .validate()
                    .assert_equal("status_code", 999)
                ),
            ]

        case = _FailOnSecond()
        with self.assertRaises(exceptions.ValidationFailure):
            case.test_start()

        summary = case.get_summary()
        self.assertFalse(summary.success, "失败用例的 summary.success 不能是 True（H1）")
        self.assertEqual(
            [step_result.name for step_result in summary.step_results],
            ["first ok", "second fails"],
            "失败的那一步必须留在 step_results 里",
        )
        self.assertFalse(summary.step_results[-1].success)
        self.assertIsNotNone(summary.step_results[-1].data)

    def test_failure_outside_any_step_is_still_not_successful(self):
        """用例级事实来源：异常发生在 step 之外（一步都没跑）时也要报失败。

        这一条覆盖的正是「只靠 `__step_results` 推导」修不好的那半边：
        列表是空的，但用例确实失败了。
        """

        class _BrokenSteps(InterfaceTester):
            config = Config("h1 no-step probe").base_url(HTTP_BIN_URL)

            @property
            def teststeps(self):
                raise exceptions.ParamsError("steps 装配失败（模拟 step 之外的异常）")

        case = _BrokenSteps()
        with self.assertRaises(exceptions.ParamsError):
            case.test_start()

        summary = case.get_summary()
        self.assertFalse(
            summary.success,
            "一步都没跑但抛了异常 → 不能报成功（修复前这里会是 success=True）",
        )
        self.assertEqual(summary.step_results, [])


# ===========================================================================
# M6：不得覆盖用户的 conftest.py
# ===========================================================================
class TestSaveTestsDoesNotClobberUserConftest(unittest.TestCase):
    """M6：`--save-tests` 会往**项目根**写 `conftest.py`。

    修复前是无条件的 `open(path, "w")` —— 用户自己的 fixture 被整体覆盖、无备份。
    正确行为：
      ① 没有 conftest.py → 正常生成（原行为）；
      ② 已有**我们生成的**（带 marker）→ 允许刷新（升级时才拿得到新版模板）；
      ③ 已有**用户自己的**（无 marker）→ **绝不覆盖**，并给出可操作的指引。
    """

    def setUp(self):
        self.tmp_dirs = []
        # NOTICE: 必须清掉全局 project_meta。
        # `loader.load_project_meta` 有一条「路径落在已加载 RootDir 之内就直接复用」的快路径
        # （loader.py:574-580），于是**先**加载过仓库根的测试会让这里的临时项目
        # 也解析成「仓库根」→ 生成物写到仓库根、而不是临时项目里。
        # 这是既有快路径的已知副作用（已在缺陷汇总里单独记录，本批次不改 loader），
        # 测试侧按全仓惯例自行 reset（见 tests/parser_test.py、tests/cli_test.py）。
        loader.reset_project_meta()

    def tearDown(self):
        loader.reset_project_meta()
        for tmp_dir in self.tmp_dirs:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    def _make(self, conftest_content=None, conftest_name="conftest.py"):
        tmp_dir, yml_path = _make_tmp_project(
            with_conftest=conftest_content, conftest_name=conftest_name
        )
        self.tmp_dirs.append(tmp_dir)
        return tmp_dir, yml_path

    def test_creates_conftest_when_absent(self):
        """① 原行为必须保留（否则 --save-tests 直接不可用）。"""
        tmp_dir, yml_path = self._make()

        compat._generate_conftest_for_summary([yml_path])

        conftest_path = os.path.join(tmp_dir, "conftest.py")
        self.assertTrue(os.path.isfile(conftest_path))
        with open(conftest_path, encoding="utf-8") as f:
            self.assertIn("session_fixture", f.read())

    def test_refreshes_our_own_generated_conftest(self):
        """② 带 marker 的是我们生成的 → 允许刷新。"""
        tmp_dir, yml_path = self._make(conftest_content=CONFTEST_MARKER + "\n# 旧版本\n")

        compat._generate_conftest_for_summary([yml_path])

        with open(os.path.join(tmp_dir, "conftest.py"), encoding="utf-8") as f:
            content = f.read()
        self.assertIn("session_fixture", content)
        self.assertNotIn("# 旧版本", content, "我们生成的旧文件应当被新版覆盖")

    def test_foreign_conftest_is_not_overwritten(self):
        """③ 用户自己的 conftest.py 必须**逐字节**保持不变。"""
        tmp_dir, yml_path = self._make(conftest_content=FOREIGN_CONFTEST)
        conftest_path = os.path.join(tmp_dir, "conftest.py")

        with open(conftest_path, encoding="utf-8") as f:
            before = f.read()

        with self.assertRaises(SystemExit) as ctx:
            compat._generate_conftest_for_summary([yml_path])

        self.assertEqual(ctx.exception.code, 1)

        with open(conftest_path, encoding="utf-8") as f:
            after = f.read()

        self.assertEqual(before, after, "用户的 conftest.py 被改动了！")
        self.assertIn("my_own_fixture", after, "用户 fixture 必须还在")

    def test_foreign_conftest_conflict_gives_actionable_guidance(self):
        """③ 的补充：不能只是"拒绝"，必须告诉用户怎么继续。

        做法：把**本该写进去的内容**落到旁边一个独立文件，用户可以直接比对/合并，
        而不是拿到一个"拒绝了"就没有下文的死胡同。
        """
        tmp_dir, yml_path = self._make(conftest_content=FOREIGN_CONFTEST)

        with self.assertRaises(SystemExit):
            compat._generate_conftest_for_summary([yml_path])

        side_candidates = [
            name
            for name in os.listdir(tmp_dir)
            if name.startswith("conftest.py") and name != "conftest.py"
        ]
        self.assertTrue(
            side_candidates,
            f"拒绝了覆盖却没有留下可用的替代文件（目录内容：{os.listdir(tmp_dir)}）",
        )

        with open(os.path.join(tmp_dir, side_candidates[0]), encoding="utf-8") as f:
            side_content = f.read()
        self.assertIn("session_fixture", side_content, "替代文件里应当是完整的 conftest 内容")

    def test_empty_conftest_is_treated_as_foreign(self):
        """空文件 / 无 marker 一律按"用户的文件"处理（保守方向：不覆盖）。"""
        tmp_dir, yml_path = self._make(conftest_content="")

        with self.assertRaises(SystemExit):
            compat._generate_conftest_for_summary([yml_path])

        self.assertEqual(
            os.path.getsize(os.path.join(tmp_dir, "conftest.py")), 0
        )

    def test_marker_not_on_first_line_is_treated_as_foreign(self):
        """marker 只在**首行**才算数（避免用户的注释里恰好提到这句话就被判定为"我们的"）。"""
        tmp_dir, yml_path = self._make(
            conftest_content='"""说明：本文件曾被 ' + CONFTEST_MARKER + ' 覆盖过。"""\n'
        )

        with self.assertRaises(SystemExit):
            compat._generate_conftest_for_summary([yml_path])


# ===========================================================================
# 批次 A / M7：记录层字段不得是「看起来像答案的假数据」
# ===========================================================================
class TestStepResultRecordFieldsAreHonest(unittest.TestCase):
    """M7：`StepResult.content_size` 与失败 step 的 `step_type` 必须是真的。

    修复前（实测 `.tmp_audit/kernel/p1`，summary.json 的 records）：

    ```text
    { "name": "步骤1（GET /ok）", "step_type": "request", "success": true,
      "elapsed": 0.0075, "content_size": 0, "export_vars": {}, "attachment": "" }
    # 同一条记录里的 data.stat：
    {"content_size": 44, ...}          ← 同一条记录内部自相矛盾（0 vs 44）
    ```

    - `content_size` **全仓没有任何写入点**（`client.py` 写的是
      `SessionData.stat.content_size`，那是另一个字段）；
    - 失败 step 的 `step_type` 来自 `step.type()`，而它写的是
      `f"request-{MethodEnum.GET}"` —— Python 3.11+ 下 `f"{枚举}"` 得到
      **`MethodEnum.GET`**（不是 `GET`），于是报告里出现 `request-MethodEnum.GET`。
    """

    def _run_pass_case(self):
        class _OkCase(InterfaceTester):
            config = Config("m7 probe").base_url(HTTP_BIN_URL)
            teststeps = [
                Step(
                    # NOTICE: 必须选一个**响应体非空**的端点：mock 的 `/status/200`
                    # 返回空体（`Content-Length: 0`），用它断言不出「0 vs 真实值」这个矛盾。
                    RunRequest("simple get")
                    .get("/get")
                    .validate()
                    .assert_equal("status_code", 200)
                )
            ]

        case = _OkCase()
        case.test_start()
        return case.get_summary()

    def test_content_size_is_recorded_not_zero(self):
        summary = self._run_pass_case()
        step_result = summary.step_results[0]

        self.assertGreater(
            step_result.content_size,
            0,
            "StepResult.content_size 恒为 0（M7 修复前形态）",
        )
        # 与同一记录里的 data.stat 口径一致（这条才是真正的护栏：
        # 单独看 0 无害，**两个字段互相矛盾**才是「假数据」）
        self.assertEqual(
            step_result.content_size,
            step_result.data.stat.content_size,
            "content_size 与 data.stat.content_size 口径不一致",
        )

    def test_failed_request_step_type_has_no_enum_repr(self):
        class _FailCase(InterfaceTester):
            config = Config("m7 step_type probe").base_url(HTTP_BIN_URL)
            teststeps = [
                Step(
                    RunRequest("will fail")
                    .get("/status/200")
                    .validate()
                    .assert_equal("status_code", 999)
                )
            ]

        case = _FailCase()
        with self.assertRaises(exceptions.ValidationFailure):
            case.test_start()

        summary = case.get_summary()
        step_type = summary.step_results[-1].step_type

        self.assertNotIn(
            "MethodEnum",
            step_type,
            f"step_type 泄漏了枚举 repr（M7 修复前形态）：{step_type!r}",
        )
        self.assertEqual(step_type, "request-GET")

    def test_successful_request_step_type_is_unchanged(self):
        """反向护栏：**成功**路径的 `step_type`（`"request"`）逐字不变。

        SQL/thrift 两个模块同样是「成功记短名（`sql`/`thrift`）、失败记富名
        （`sql-request-…`/`thrift-request-…`）」，那是 0919-18 有意建立的口径
        （`tests/step_sql_request_test.py` 有护栏钉住失败侧的富名）。
        本次只修「枚举 repr 泄漏」，不动这个约定。
        """
        summary = self._run_pass_case()
        self.assertEqual(summary.step_results[0].step_type, "request")


# ===========================================================================
# 批次 B / M3 + M4：`--save-tests` 的**用例路径判定**与 **conftest 落点**
# ===========================================================================
class TestSaveTestsPathAndLocation(unittest.TestCase):
    """M3：判据不能是「这个 token 存在」，而是「上一个 token 是不是取值的选项」。

    ## 修复前的现场（实测三组，退出码全是 0）

    ```text
    hrun -c pytest.ini case.yml --save-tests            → logs/pytest.summary.json
    hrun --junitxml reports/out.xml case.yml --save-tests → logs/reports/out.summary.json
    hrun -c sub/pytest.ini case.yml --save-tests        → 在 sub/ 写 conftest.py，**不产出** summary
    ```

    根因：`_generate_conftest_for_summary` 用 `for arg in args: if os.path.exists(arg): break`
    猜用例路径，而**选项的值**本身也可以是存在的路径。同一份判据在 `cli.main_run` 里
    早就有了（批次 7 / M2），但那个调用点没复用它 —— 现在收口成
    `compat.filter_test_paths` + `compat.PYTEST_OPTIONS_WITH_VALUE` **唯一一份**。

    M4：找不到项目标记时，**不许**写到祖先目录（`load_project_meta` 会兜底成
    「当前已加载的 meta / cwd」）—— 实测把 conftest.py 写到了**仓库根**，
    而它里面的 `summary_path` 是硬编码的，会连带劫持同目录树下其它 pytest 会话的汇总输出。
    """

    def setUp(self):
        loader.reset_project_meta()
        self.tmp_dir, self.yml_path = _make_tmp_project()

    def tearDown(self):
        loader.reset_project_meta()
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    # ---------------------------------------------------------------- M3 单元
    def test_option_value_is_not_treated_as_a_test_path(self):
        ini_path = os.path.join(self.tmp_dir, "pytest.ini")
        with open(ini_path, "w", encoding="utf-8") as f:
            f.write("[pytest]\naddopts = -q\n")

        test_paths, remaining = compat.filter_test_paths(
            ["-c", ini_path, self.yml_path, "--save-tests"]
        )

        self.assertEqual(test_paths, [self.yml_path], "选项的值被当成了用例路径（M3）")
        self.assertIn(ini_path, remaining)
        self.assertIn("--save-tests", remaining)

    def test_equals_form_is_naturally_safe(self):
        test_paths, remaining = compat.filter_test_paths(
            [f"--rootdir={self.tmp_dir}", self.yml_path]
        )

        self.assertEqual(test_paths, [self.yml_path])
        self.assertIn(f"--rootdir={self.tmp_dir}", remaining)

    def test_multiple_test_paths_are_all_collected(self):
        second = os.path.join(self.tmp_dir, "second.yml")
        with open(second, "w", encoding="utf-8") as f:
            f.write("config:\n    name: second\n")

        test_paths, _remaining = compat.filter_test_paths([self.yml_path, second])

        self.assertEqual(test_paths, [self.yml_path, second])

    # ---------------------------------------------------------------- M3 端到端（conftest 内容）
    def _generated_summary_path(self, args, conftest_dir: str = None) -> str:
        """跑一次 conftest 生成，把生成物里**硬编码的 summary 路径**取出来。

        `conftest_dir` 默认为 `setUp` 建的项目目录；M4 那条用例的落点是
        「用例自己所在目录」，所以要把目录传进来。
        """
        compat._generate_conftest_for_summary(args)

        conftest_path = os.path.join(conftest_dir or self.tmp_dir, "conftest.py")
        with open(conftest_path, encoding="utf-8") as f:
            content = f.read()

        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("summary_path ="):
                raw_value = stripped.split("=", 1)[1].strip()
                # 生成物里写的是原始字符串字面量：`summary_path = r"D:\..."`
                if raw_value.startswith("r"):
                    raw_value = raw_value[1:]
                return raw_value.strip().strip('"')
        raise AssertionError(f"生成物里没有 summary_path：\n{content[:400]}")

    def test_summary_name_follows_the_case_not_the_option_value(self):
        ini_path = os.path.join(self.tmp_dir, "pytest.ini")
        with open(ini_path, "w", encoding="utf-8") as f:
            f.write("[pytest]\n")

        summary_path = self._generated_summary_path(
            ["-c", ini_path, self.yml_path, "--save-tests"]
        )

        self.assertTrue(
            summary_path.endswith(os.path.join("logs", "case.summary.json")),
            f"summary 名字跟着**选项的值**走了（M3 修复前形态）：{summary_path}",
        )

    def test_multiple_cases_produce_all_summary_json(self):
        second = os.path.join(self.tmp_dir, "second.yml")
        with open(second, "w", encoding="utf-8") as f:
            f.write("config:\n    name: second\n")

        summary_path = self._generated_summary_path([self.yml_path, second])

        self.assertTrue(
            summary_path.endswith(os.path.join("logs", "all.summary.json")),
            f"多用例应当与目录同口径产出 all.summary.json：{summary_path}",
        )

    # ---------------------------------------------------------------- M4
    def test_markerless_case_dir_does_not_write_to_an_ancestor(self):
        """无项目标记时 conftest.py 落在**用例自己的目录**，绝不落在祖先目录。

        NOTICE: `_make_tmp_project()` 建的项目是**有** `debugtalk.py` 的，
        所以这里另建一个「整条祖先链都没有 debugtalk.py」的目录才有意义
        （`logs/tmp_*` 的上层就是仓库根，它没有 debugtalk.py）。
        """
        markerless_dir = os.path.join(
            os.getcwd(), "logs", f"tmp_markerless_{uuid.uuid4().hex[:8]}"
        )
        os.makedirs(markerless_dir, exist_ok=True)
        case_path = os.path.join(markerless_dir, "case.yml")
        with open(case_path, "w", encoding="utf-8") as f:
            f.write("config:\n    name: markerless\n")

        try:
            root_conftest = os.path.join(os.getcwd(), "conftest.py")
            existed_before = os.path.isfile(root_conftest)

            loader.reset_project_meta()
            summary_path = self._generated_summary_path(
                [case_path, "--save-tests"], conftest_dir=markerless_dir
            )

            self.assertTrue(
                os.path.isfile(os.path.join(markerless_dir, "conftest.py")),
                "conftest.py 应当落在用例自己所在的目录（M4）",
            )
            self.assertTrue(
                summary_path.startswith(markerless_dir),
                f"summary 应当落在用例目录之下：{summary_path}",
            )

            # NOTICE（护栏写法）：不能只断言「仓库根没有 conftest.py」——那份文件可能
            # 本来就存在（与本次无关）。真正的不变量是「**本次调用**没有往祖先目录写」：
            #   - 本次之前不存在 → 之后也不该存在；
            #   - 本来就存在 → 内容里绝不能出现本次的用例目录
            #     （修复前的 bug 会把 summary_path 硬编码成用例目录下的路径）。
            if existed_before:
                with open(root_conftest, encoding="utf-8") as f:
                    self.assertNotIn(
                        markerless_dir,
                        f.read(),
                        "conftest.py 被写到了仓库根，且指向本次的用例目录（M4 修复前的事故形态）",
                    )
            else:
                self.assertFalse(
                    os.path.isfile(root_conftest),
                    "不许把 conftest.py 写到仓库根（M4 修复前的事故形态）",
                )
        finally:
            loader.reset_project_meta()
            shutil.rmtree(markerless_dir, ignore_errors=True)


class TestGeneratedConftestIsValidPython(unittest.TestCase):
    """生成物必须是**合法 Python** —— 这条单独钉住，因为模板是"字符串里的代码"。

    NOTICE: 这是一个真实踩过的坑。往模板里加多行日志时写了 `\\n`（在 compat.py 的
    普通三引号字符串里，单个 `\\n` 会被解析成**真实换行**），于是生成出来的 f-string
    跨行、直接 `SyntaxError: unterminated f-string literal`。
    失败现场很隐蔽：`hrun --save-tests` 报的是 pytest 的
    `ImportError while loading conftest.py`，而错误文件是**生成物**、不是源码。

    这条测试把"生成物可编译"变成一步就能验证的事（`emit_yaml.validate_emitted_case`
    对生成的 `_test.py` 也有同样的 `compile()` 兜底，口径一致）。
    """

    def setUp(self):
        loader.reset_project_meta()
        self.tmp_dir, self.yml_path = _make_tmp_project()

    def tearDown(self):
        loader.reset_project_meta()
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def test_generated_conftest_compiles(self):
        compat._generate_conftest_for_summary([self.yml_path])

        conftest_path = os.path.join(self.tmp_dir, "conftest.py")
        with open(conftest_path, encoding="utf-8") as f:
            content = f.read()

        compile(content, conftest_path, "exec")  # 不抛 SyntaxError 即通过

    def test_generated_conftest_has_no_stray_template_artifacts(self):
        """生成物里不该留下模板替换的残骸，也不该留下未插值的 `{{...}}`。"""
        compat._generate_conftest_for_summary([self.yml_path])

        with open(os.path.join(self.tmp_dir, "conftest.py"), encoding="utf-8") as f:
            content = f.read()

        self.assertNotIn("{{", content, "模板花括号写成了双层，生成物里没有被插值")
        self.assertNotIn("SUMMARY_PATH_PLACEHOLDER", content)
        self.assertTrue(content.startswith(CONFTEST_MARKER), "首行必须是 marker")
        # 汇总路径要真的被替换成绝对路径
        self.assertIn(self.tmp_dir, content)


# ===========================================================================
# 批次 A / H3 + M8：**配置解析阶段**失败也必须报失败，汇总统计不得出现负数
# ===========================================================================
class TestConfigStageFailureIsReportedAsFailure(unittest.TestCase):
    """H3 端到端：`test_start` **每个阶段**的失败都要进「用例级事实来源」。

    ## 修复前的现场（实测，真 CLI：`hrun case.yml --save-tests`，config.timeout 非法）

    ```text
    内层 pytest：1 failed、子进程退出码 1
    logs/case.summary.json：
      success = True                              ← 与退出码直接矛盾
      stat    = {'testcases': {'total': 1, 'success': 1, 'fail': 0}, ...}
      details[0].success = True
      details[0].records = []
      details[0].time.duration = 0.0
      details[0].log = <一个不存在的 .run.log 路径>
      logs/ 目录里：只有 all/case.summary.json，**一个 .run.log 都没有**
    ```

    两处根因（`runner.test_start`）：`_setup_runner` / 挂 sink / `__parse_config` 都在
    那个设 `__failed = True` 的 `try` **之外**，而 `__duration` 更是在 `finally` **之后**赋值。

    触发面很宽，且都是**用户最常见的写错**：`config.timeout` 非法、
    `config.variables` 里 `${ENV(缺失)}`、`config.base_url` 解析失败……
    """

    def setUp(self):
        loader.reset_project_meta()
        self.tmp_dir, self.yml_path = _make_tmp_project()

    def tearDown(self):
        loader.reset_project_meta()
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def _run_save_tests(self, config_extra: str):
        with open(self.yml_path, "w", encoding="utf-8") as f:
            f.write(
                f"config:\n"
                f"    name: config stage probe\n"
                f"    base_url: {HTTP_BIN_URL}\n"
                f"{config_extra}"
                f"teststeps:\n"
                f"    -\n"
                f"        name: never runs\n"
                f"        request:\n"
                f"            method: GET\n"
                f"            url: /status/200\n"
                f"        validate:\n"
                f'            - eq: ["status_code", 200]\n'
            )

        env = dict(os.environ)
        env["PYTHONIOENCODING"] = "utf-8"
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "interfacetester",
                "run",
                "case.yml",
                "--save-tests",
            ],
            cwd=self.tmp_dir,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env,
            timeout=180,
        )

        summary_path = os.path.join(self.tmp_dir, "logs", "case.summary.json")
        self.assertTrue(
            os.path.isfile(summary_path),
            f"summary.json 没有被生成\nreturncode={proc.returncode}\n"
            f"stdout=\n{proc.stdout}\nstderr=\n{proc.stderr}",
        )
        with open(summary_path, encoding="utf-8") as f:
            return proc, json.load(f)

    def test_bad_config_timeout_is_reported_as_failure(self):
        proc, summary = self._run_save_tests('    timeout: "not-a-number"\n')

        self.assertNotEqual(proc.returncode, 0, "配置解析失败必须是非零退出码")

        self.assertFalse(
            summary["success"],
            "配置解析阶段失败被报成通过（H3）："
            f"{json.dumps(summary, ensure_ascii=False)[:400]}",
        )
        self.assertEqual(
            summary["stat"]["testcases"],
            {"total": 1, "success": 0, "fail": 1},
            "失败用例在 stat.testcases 里必须记成 fail",
        )
        self.assertFalse(summary["details"][0]["success"])

        # 记录为空是对的（一个 step 都没跑），但**绝不能是负数**（M8 的修复前形态）
        for key, value in summary["stat"]["teststeps"].items():
            self.assertGreaterEqual(
                value,
                0,
                f"stat.teststeps.{key} 出现了负数（M8 修复前形态）："
                f"{json.dumps(summary['stat'], ensure_ascii=False)}",
            )
        self.assertEqual(summary["details"][0]["records"], [])

    def test_missing_env_variable_in_config_is_reported_as_failure(self):
        """第二形态（更常见）：`config.variables` 里引用了不存在的 ENV。"""
        proc, summary = self._run_save_tests(
            '    variables:\n        token: "${ENV(ABSENT_TOKEN_FOR_PROBE)}"\n'
        )

        self.assertNotEqual(proc.returncode, 0)
        self.assertFalse(summary["success"])
        self.assertEqual(summary["stat"]["testcases"]["fail"], 1)

    def test_failing_case_duration_is_not_zero(self):
        """M7：失败用例的耗时不能记成 0（`__duration` 原先在 `finally` 之后赋值）。

        NOTICE（为什么用 `sleep` 造一个**可测的**耗时）：`time.time()` 的分辨率有限，
        配置解析失败往往在同一时刻刻度内完成 —— `time.time() - __start_at` 可能
        **恰好等于 0.0**，于是「断言 > 0」会随机变红。这类「靠碰运气」的护栏本身就是
        新的抽风源（见 `docs/架构与调用链.md` §十 第 3 条）。
        这里在配置解析阶段里插一个 `${sleep(0.05)}`：它**先**执行、失败的 timeout 在**后**，
        因此用例级耗时必然 ≥ 0.05s，断言 `>= 0.04`（留调度余量）是确定性的。
        """
        _, summary = self._run_save_tests(
            '    variables:\n'
            '        slow: "${sleep(0.05)}"\n'
            '    timeout: "not-a-number"\n'
        )

        self.assertGreaterEqual(
            summary["details"][0]["time"]["duration"],
            0.04,
            "失败用例的 duration 恒为 0（M7 修复前形态）",
        )

    def test_summary_log_path_points_to_an_existing_file(self):
        """H3 连带：summary 里的 `log` 字段不得指向**不存在**的文件。

        修复前配置阶段失败的用例从不挂 sink → `logs/` 下一个 `.run.log` 都没有，
        而 `log` 字段照样写着那个路径。现在 sink 提前到 `__parse_config` **之前**挂，
        所以这类失败也会留下日志；万一某条路径仍然没挂上，`log` 必须是空串而不是野指针。
        """
        _, summary = self._run_save_tests('    timeout: "not-a-number"\n')

        log_path = summary["details"][0]["log"]
        if log_path:
            self.assertTrue(
                os.path.isfile(log_path),
                f"summary 里的 log 指向一个不存在的文件：{log_path}",
            )

        # 本用例的形态（配置阶段失败）必须**真的留下**日志文件
        run_logs = [
            name
            for name in os.listdir(os.path.join(self.tmp_dir, "logs"))
            if name.endswith(".run.log")
        ]
        self.assertTrue(
            run_logs,
            "配置解析阶段失败的用例也应该留下 .run.log（失败必须留证据）",
        )
