# NOTE: Generated By InterfaceTester 5.0.1
# FROM: 01_create_and_read.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseT01CreateAndRead(InterfaceTester):

    config = (
        Config("01 数据管理：造数与回读")
        .variables(
            **{
                "token": "${ENV(DM_TOKEN)}",
                "suffix": "alpha",
                "record_id": "${create_record($suffix)}",
                "run_prefix": "${run_prefix()}",
            }
        )
        .base_url("${api_base()}")
    )

    teststeps = [
        Step(
            RunRequest("刚造的数据可以被读到")
            .get("/records/$record_id")
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_startswith("body.name", "${case_prefix()}")
        ),
        Step(
            RunRequest("本次运行里只应有这一条数据")
            .get("/records")
            .with_params(**{"prefix": "$run_prefix"})
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.count", 1)
            .assert_equal("body.records[0].id", "$record_id")
        ),
        Step(
            RunRequest("未带 token 时被拒绝（顺便证明鉴权链路是通的）")
            .get("/records")
            .with_headers(**{"X-No-Auth": "1"})
            .validate()
            .assert_equal("status_code", 401)
        ),
    ]


if __name__ == "__main__":
    TestCaseT01CreateAndRead().test_start()
