# NOTE: Generated By InterfaceTester 5.0.1
# FROM: 02_isolation_check.yml
import pytest

from interfacetester import InterfaceTester, Config, Step, RunRequest
from interfacetester import Parameters


class TestCaseT02IsolationCheck(InterfaceTester):

    @pytest.mark.parametrize("param", Parameters({"round": [1, 2]}))
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("02 数据隔离与回收（同一用例跑两轮：第二轮必须看不到第一轮的数据）")
        .variables(**{"token": "${ENV(DM_TOKEN)}", "run_prefix": "${run_prefix()}"})
        .base_url("${api_base()}")
    )

    teststeps = [
        Step(
            RunRequest("开跑前：本次运行不应有任何残留数据")
            .get("/records")
            .with_params(**{"prefix": "$run_prefix"})
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.count", 0)
        ),
        Step(
            RunRequest("造自己的数据（前缀只属于自己的这一轮）")
            .with_variables(
                **{
                    "suffix": "round$round",
                    "record_id": "${create_record($suffix)}",
                    "case_prefix": "${case_prefix()}",
                }
            )
            .get("/records")
            .with_params(**{"prefix": "$run_prefix"})
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.count", 1)
            .assert_equal("body.records[0].id", "$record_id")
            .assert_startswith("body.records[0].name", "$case_prefix")
        ),
    ]


if __name__ == "__main__":
    TestCaseT02IsolationCheck().test_start()
