# NOTE: Generated By InterfaceTester 5.0.1
# FROM: 03_dangerous_ops.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseT03DangerousOps(InterfaceTester):

    config = (
        Config("03 危险操作：全库清空的闸门（生产环境会被 conftest 跳过）")
        .variables(
            **{
                "token": "${ENV(DM_TOKEN)}",
                "run_prefix": "${run_prefix()}",
                "reset_result": "${reset_store()}",
            }
        )
        .base_url("${api_base()}")
    )

    teststeps = [
        Step(
            RunRequest("闸门开着时：全库清空被执行，本次运行的数据也被一并清掉")
            .get("/records")
            .with_params(**{"prefix": "$run_prefix"})
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.count", 0)
        ),
        Step(
            RunRequest("不带危险头时：即使是合法请求也被服务端 403 拒绝")
            .delete("/records")
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 403)
        ),
    ]


if __name__ == "__main__":
    TestCaseT03DangerousOps().test_start()
