# NOTE: Generated By InterfaceTester 5.0.1
# FROM: body_forms.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseBodyForms(InterfaceTester):

    config = Config(
        "body forms demo (json / params / urlencoded / upload / raw)"
    ).base_url("${get_httpbin_server()}")

    teststeps = [
        Step(
            RunRequest("JSON body - 创建用户")
            .post("/post")
            .with_json({"username": "demo", "age": 20, "tags": ["admin", "vip"]})
            .extract()
            .with_jmespath("body.json.username", "creator")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.method", "POST")
            .assert_equal("body.json.username", "demo")
            .assert_equal("body.json.tags", ["admin", "vip"])
            .assert_equal('body.headers."Content-Type"', "application/json")
        ),
        Step(
            RunRequest("Query String - params 传参")
            .get("/get")
            .with_params(**{"page": 1, "size": 20, "keyword": "测试文件"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.page", "1")
            .assert_equal("body.args.size", "20")
            .assert_equal("body.args.keyword", "测试文件")
        ),
        Step(
            RunRequest("token - body 的 x-www-form-urlencoded")
            .post("/post")
            .with_headers(**{"Content-Type": "application/x-www-form-urlencoded"})
            .with_data(
                "grant_type=client_credentials&client_id=demo_client&client_secret=demo_secret"
            )
            .extract()
            .with_jmespath("body.form.client_id", "demo_token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'body.headers."Content-Type"', "application/x-www-form-urlencoded"
            )
            .assert_equal("body.form.grant_type", "client_credentials")
            .assert_equal("body.form.client_id", "demo_client")
        ),
        Step(
            RunRequest("上传文件 - body 的 form-data")
            .post("/post")
            .upload(**{"file": "files/demo.txt", "scene": "avatar"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_startswith('body.headers."Content-Type"', "multipart/form-data")
        ),
        Step(
            RunRequest("删除文件 - body 的 raw 传参")
            .delete("/delete")
            .with_headers(**{"Content-Type": "application/json"})
            .with_data('{"file_ids": ["f-1", "f-2"], "operator": "$creator"}')
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.method", "DELETE")
            .assert_equal(
                "body.data", '{"file_ids": ["f-1", "f-2"], "operator": "demo"}'
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseBodyForms().test_start()
