# NOTE: Generated By InterfaceTester 5.0.1
# FROM: examples\httpbin_demo.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseHttpbinDemo(InterfaceTester):

    config = (
        Config("interfacetester demo").base_url("https://httpbin.org").verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get request with params")
            .get("/get")
            .with_params(**{"foo": "bar"})
            .extract()
            .with_jmespath("body.origin", "origin")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.args.foo", "bar")
        ),
        Step(
            RunRequest("post json with extracted variable")
            .post("/post")
            .with_json({"name": "interfacetester", "origin": "$origin"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.json.name", "interfacetester")
            .assert_equal("body.json.origin", "$origin")
        ),
    ]


if __name__ == "__main__":
    TestCaseHttpbinDemo().test_start()
