# NOTE: Generated By InterfaceTester 5.0.1
# FROM: auth_login.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseAuthLogin(InterfaceTester):

    config = Config("登录 - 获取 access token").base_url("${api_base()}").verify(False)

    teststeps = [
        Step(
            RunRequest("获取 access token")
            .post("/oauth2/token")
            .with_headers(**{"Content-Type": "application/x-www-form-urlencoded"})
            .with_data(
                {
                    "grant_type": "client_credentials",
                    "client_id": "${ENV(UNIFSP_CLIENT_ID)}",
                    "client_secret": "${ENV(UNIFSP_CLIENT_SECRET)}",
                }
            )
            .extract()
            .with_jmespath("body.access_token", "token")
            .validate()
            .assert_equal("body.token_type", "Bearer")
            .assert_type_match("body.access_token", "str")
        ),
    ]


if __name__ == "__main__":
    TestCaseAuthLogin().test_start()
