# NOTE: Generated By InterfaceTester 5.0.1
# FROM: directory_create.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseDirectoryCreate(InterfaceTester):

    config = (
        Config("创建目录")
        .variables(**{"app_path": "${app_path()}", "test_dir": "${test_dir()}"})
        .base_url("${api_base()}")
        .verify(False)
        .oauth2()
        .token_url("${token_url()}")
        .client_id("${ENV(UNIFSP_CLIENT_ID)}")
        .client_secret("${ENV(UNIFSP_CLIENT_SECRET)}")
    )

    teststeps = [
        Step(
            RunRequest("创建测试目录")
            .post("/api/directory/create")
            .with_json({"path": "$test_dir"})
            .with_x_path("$app_path")
            .validate()
            .assert_equal("body.success", True)
            .assert_equal("body.errorCode", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseDirectoryCreate().test_start()
