# NOTE: Generated By InterfaceTester 5.0.1
# FROM: file_delete.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseFileDelete(InterfaceTester):

    config = (
        Config("删除文件")
        .variables(**{"app_path": "${app_path()}", "test_dir": "${test_dir()}"})
        .base_url("${api_base()}")
        .verify(False)
        .oauth2()
        .token_url("${token_url()}")
        .client_id("${ENV(UNIFSP_CLIENT_ID)}")
        .client_secret("${ENV(UNIFSP_CLIENT_SECRET)}")
    )

    teststeps = [
        Step(
            RunRequest("创建测试目录")
            .post("/api/directory/create")
            .with_json({"path": "$test_dir"})
            .with_x_path("$app_path")
            .validate()
            .assert_equal("body.success", True)
        ),
        Step(
            RunRequest("上传文件")
            .post("/api/file/upload")
            .upload(**{"path": "$test_dir", "files": "test_files/测试文件.txt"})
            .with_x_path("$test_dir")
            .validate()
            .assert_equal("body.success", True)
        ),
        Step(
            RunRequest("删除文件")
            .post("/api/file/delete")
            .with_json({"fileName": "测试文件.txt", "path": "$test_dir"})
            .with_x_path("$test_dir")
            .validate()
            .assert_equal("body.success", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseFileDelete().test_start()
