# NOTE: Generated By InterfaceTester 5.0.1
# FROM: md5_sign_demo.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseMd5SignDemo(InterfaceTester):

    config = (
        Config("MD5 签名用法演示")
        .variables(
            **{
                "app_path": "${app_path()}",
                "timestamp": "${get_timestamp()}",
                "sign_secret": "${ENV(UNIFSP_CLIENT_SECRET)}",
                "sign_params": {"path": "$app_path", "timestamp": "$timestamp"},
                "sign": "${md5_sign($sign_params, $sign_secret)}",
            }
        )
        .base_url("${api_base()}")
        .verify(False)
        .oauth2()
        .token_url("${token_url()}")
        .client_id("${ENV(UNIFSP_CLIENT_ID)}")
        .client_secret("${ENV(UNIFSP_CLIENT_SECRET)}")
    )

    teststeps = [
        Step(
            RunRequest("带签名查询目录（只读，签名仅作演示）")
            .get("/api/directory/query")
            .with_params(
                **{"path": "$app_path", "timestamp": "$timestamp", "sign": "$sign"}
            )
            .with_headers(**{"X-Timestamp": "$timestamp", "X-Sign": "$sign"})
            .with_x_path("$app_path")
            .validate()
            .assert_equal("body.success", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseMd5SignDemo().test_start()
