# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_false_pass.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastFalsePass(InterfaceTester):

    config = Config("对照：假通过（GREEN 但什么都没测到）")

    teststeps = [
        Step(
            RunRequest("想断 status_code 是不是 404——但断言字段名拼错了").get(
                "${base_url()}/get"
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastFalsePass().test_start()
