# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_assert_fail.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastAssertFail(InterfaceTester):

    config = Config("对照：断言不通过（FAILED）")

    teststeps = [
        Step(
            RunRequest("期望 404，但 GET /get 实际返回 200")
            .get("${base_url()}/get")
            .validate()
            .assert_equal("status_code", 404)
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastAssertFail().test_start()
