# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_type_mismatch.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastTypeMismatch(InterfaceTester):

    config = Config("对照：期望值类型写错（FAILED）")

    teststeps = [
        Step(
            RunRequest('把数字 200 写成了字符串 "200"')
            .get("${base_url()}/get")
            .validate()
            .assert_equal("status_code", "200")
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastTypeMismatch().test_start()
