# NOTE: Generated By InterfaceTester 5.0.1
# FROM: contrast_env_missing.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseContrastEnvMissing(InterfaceTester):

    config = Config("对照：引用了不存在的环境变量（FAILED / 请求未发出）")

    teststeps = [
        Step(
            RunRequest("地址里引用了没定义过的环境变量")
            .get("${ENV(NOT_DEFINED_ON_PURPOSE)}/get")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseContrastEnvMissing().test_start()
