# NOTE: Generated By InterfaceTester 5.0.1
# FROM: hello.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseHello(InterfaceTester):

    config = Config("我的第一条用例")

    teststeps = [
        Step(
            RunRequest("调一次 GET 接口")
            .get("${ENV(BASE_URL)}/get")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseHello().test_start()
