# NOTE: Generated By InterfaceTester 5.0.1
# FROM: hello_func.yml
from interfacetester import InterfaceTester, Config, Step, RunRequest


class TestCaseHelloFunc(InterfaceTester):

    config = Config("用 debugtalk 的函数拿地址")

    teststeps = [
        Step(
            RunRequest("调一次 GET 接口")
            .get("${base_url()}/get")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseHelloFunc().test_start()
